modLoader="javafml"
loaderVersion="[1,)"
license="LGPL-3.0"

[[mods]]
modId="valcon"
version="0.1"
displayName="Valcon"
description='''
An addon and core mod for the Starfell modpacks. Let the stars guide you!
'''

[[dependencies.valcon]]
modId="farmersdelight"
mandatory=true
versionRange="[1.21,)"
ordering="AFTER"
side="BOTH"
